config/routes.rb
Rails.application.routes.draw do
  root 'peoducts#index'
  resources :peoducts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/peoduct.rb
class Peoduct < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/peoducts_controller.rb
class PeoductsController < ApplicationController
  before_action :set_peoduct, only: %i[ show edit update destroy ]

  # GET /peoducts or /peoducts.json
  def index
    @peoducts = Peoduct.all
  end

  # GET /peoducts/1 or /peoducts/1.json
  def show
  end

  # GET /peoducts/new
  def new
    @peoduct = Peoduct.new
  end

  # GET /peoducts/1/edit
  def edit
  end

  # POST /peoducts or /peoducts.json
  def create
    @peoduct = Peoduct.new(peoduct_params)

    respond_to do |format|
      if @peoduct.save
        format.html { redirect_to @peoduct, notice: "Peoduct was successfully created." }
        format.json { render :show, status: :created, location: @peoduct }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @peoduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peoducts/1 or /peoducts/1.json
  def update
    respond_to do |format|
      if @peoduct.update(peoduct_params)
        format.html { redirect_to @peoduct, notice: "Peoduct was successfully updated." }
        format.json { render :show, status: :ok, location: @peoduct }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @peoduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peoducts/1 or /peoducts/1.json
  def destroy
    @peoduct.destroy
    respond_to do |format|
      format.html { redirect_to peoducts_url, notice: "Peoduct was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peoduct
      @peoduct = Peoduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def peoduct_params
      params.require(:peoduct).permit(:name, :price, :vendor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peoducts_helper.rb
module PeoductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductRegister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peoducts/_form.html.erb
<%= form_with(model: peoduct, local: true) do |form| %>
  <% if peoduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peoduct.errors.count, "error") %> prohibited this peoduct from being saved:</h2>

      <ul>
      <% peoduct.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :vendor %>
    <%= form.text_field :vendor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peoducts/edit.html.erb
<h1>Editing Peoduct</h1>

<%= render 'form', peoduct: @peoduct %>

<%= link_to 'Show', @peoduct %> |
<%= link_to 'Back', peoducts_path %>

app/views/peoducts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awesome Products!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Vendor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peoducts.each do |peoduct| %>
      <tr>
        <td><%= peoduct.name %></td>
        <td><%= peoduct.price %></td>
        <td><%= peoduct.vendor %></td>
        <td><%= link_to 'Show', peoduct %></td>
        <td><%= link_to 'Edit', edit_peoduct_path(peoduct) %></td>
        <td><%= link_to 'Destroy', peoduct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peoduct', new_peoduct_path %>

app/views/peoducts/new.html.erb
<h1>New Peoduct</h1>

<%= render 'form', peoduct: @peoduct %>

<%= link_to 'Back', peoducts_path %>

app/views/peoducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @peoduct.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @peoduct.price %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @peoduct.vendor %>
</p>

<%= link_to 'Edit', edit_peoduct_path(@peoduct) %> |
<%= link_to 'Back', peoducts_path %>